apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-v2-sree
  namespace: sreejeshm
  annotations:
   kubernetes.io/change-cause: "image tag updating to caddy"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
     containers:
     - name: c1
       image: caddy
