apiVersion: v1
kind: Pod
metadata: 
  name: mysqlpod-sree
  namespace: sreejeshm
  labels:
    env: dev
    user: sree
spec:
  containers:
  - name: ctr1
    image: mysql
    envFrom:
    - configMapRef:
        name: cm1
