apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-lb-sree
  namespace: sreejeshm
  annotations:
   kubernetes.io/change-cause: "image tag updating to caddy"
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
     containers:
     - name: c1
       image: nginx
