apiVersion: v1
kind: Service
metadata:
 name: canarylb-sree
 namespace: sreejeshm
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
  - port: 80  #service port inside cluster
    targetPort: 80 #container port
