apiVersion: v1
kind: Pod
metadata: 
  name: mysql-pod-sree
  namespace: sreejeshm
  labels:
    env: dev
    user: sree
spec:
  containers:
  - name: ctr1
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root123
    - name: MYSQL_DATABASE
      value: allianzdb
