apiVersion: v1
kind: Pod
metadata: 
  name: newmysqlpod-sree
  namespace: sreejeshm
  labels:
    env: dev
    user: sree
spec:
  containers:
  - name: ctr1
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: cm1
          key: root-pass
    - name: MYSQL_DATABASE
      valueFrom:
        configMapKeyRef:
          name: cm1
          key: sql-db
