apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-sree
  namespace: sreejeshm
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
     containers:
     - name: c1
       image: nginx
     - name: c2
       image: redis
